[project]
name = "jev-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "s2422114", email = "s2422114@stu.musashino-u.ac.jp" }
]
requires-python = ">=3.12.7"
dependencies = [
    "python-dotenv>=1.2.3",
    "typesafe-sdk>=0.7.0",
]

[project.scripts]
jev-app = "jev_app:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
